$(document).ready(function () {
    $('input#autocomplete-company').autocomplete({
        data: {
            "IFS": 'img/companies/ifs.png',
            "WSO2": 'img/companies/wso2.svg',
            "Google": 'img/companies/google.png'
        },
    });
    $('input#autocomplete-position').autocomplete({
        data: {
            "CEO": null,
            "Manager": null,
            "Senior Software Engineer": null,
            "Junior Software Engineer": null,
            "Associate Software Engineer": null,
            "Project Lead": null,
            "Business Analysist": null,
            "Intern": null
        },
    });
    $('input#autocomplete-school').autocomplete({
        data: {
            "University of Colombo": null,
            "Eastern University": null,
            "University of Jaffna": null,
            "University of Kelaniya": null,
            "University of Moratuwa": null,
            "Open University": null,
            "University of Peradeniya": null,
            "Rajarata University": null,
            "University of Ruhuna": null,
            "Sabaragamuwa University": null,
            "South Eastern University": null,
            "University of Sri Jayewardenepura": null,
            "Uva Wellassa University": null,
            "University of the Visual and Performing Arts": null,
            "Wayamba University": null,
            "General Sir John Kotelawala Defence University": null,
            "Sri Lanka Institute of Information Technology": null,
            "National School of Business Management": null,
            "Ananda College, Colombo": null,
            "Ananda Sastralaya, Kotte": null,
            "Ananda Balika Vidyalaya, Colombo": null,
            "Anula Vidyalaya, Nugegoda": null,
            "Asoka Vidyalaya, Colombo": null,
            "Bandaragama Central College	Bandaragama": null,
            "Bulathsinhala Central College	Bulathsinghala": null,
            "Bomiriya National School": null,
            "Buddhist Ladies' College": null,
            "C. W. W. Kannangara College": null,
            "Colombo Hindu College": null,
            "Carey College Colombo": null,
            "Defence Services School, Colombo": null,
            "D. S. Senanayake College, Colombo": null,
            "Devi Balika Vidyalaya, Colombo": null,
            "Dharmapala Vidyalaya, Kottawa": null,
            "Kolonnawa Balika Vidyalaya, Colombo": null,
            "Dharmapala Vidyalaya, Pannipitiya": null,
            "Gothami Balika Vidyalaya, Colombo": null,
            "Gurukula Maha Vidyalaya, Kelaniya": null,
            "Hanwella Rajasinghe Central College, Hanwella": null,
            "Harischandra Vidyalaya,Temple Rd, Negombo": null,
            "Hindu College, Colombo 4": null,
            "Hameed Al Husseinie College, Colombo": null,
            "Hewavitharana Maha Vidyalaya, Colombo": null,
            "Isipathana College, Colombo": null,
            "Kotahene Central College, Vidyala Mw, Colombo 13": null,
            "Lumbini College, Colombo ,5": null,
            "Mahanama College, Colombo": null,
            "Mahamaya Balika Maha Vidyalaya": null,
            "Muslims Ladies College, Colombo": null,
            "Mutwal Hindu College": null,
            "Mahinda Rajapakse National School, Pitipana, Homagama": null,
            "Nalanda Central College, Minuwangoda": null,
            "Nalanda College, Colombo": null,
            "Piliyandala Central College": null,
            "President's College, Sri Jayawardenapura Kotte": null,
            "Presbyterian Girls' National School, Dehiwala": null,
            "Prince of Wales' College, Moratuwa": null,
            "Princess of Wales' College, Moratuwa": null,
            "Hindu Ladies College, Ramanathan": null,
            "Royal College, Colombo": null,
            "Rathnawali Balika Vidyalaya, Borella": null,
            "Royal College, Horana": null,
            "Samudradevi Balika Vidyalaya Nugegoda": null,
            "Seethawaka National School, Avissawella": null,
            "Seethawaka Rajasinghe Central College	Avissawella": null,
            "Sri Dharmaloka Central College, Waragoda, Kelaniya": null,
            "Sri Sumangala Balika Maha Vidyalaya, Panadura": null,
            "Sri Sumangala Maha Vidyalaya	,Panadura": null,
            "Sripalee Vidyalaya, Horana": null,
            "St. Pauls Girls School	Milagiriya, Colombo 4": null,
            "St. Anthony's Maha School	Vincent Joseph Avenue, Wattala": null,
            "Sirimavo Bandaranaike Vidyalaya, Colombo": null,
            "Sir Baron Jayathilaka Vidyalaya, Colombo": null,
            "Sri Subhuthi National School, Battaramulla.": null,
            "St. John's College Colombo": null,
            "St. Paul's Girls School, Milagiriya": null,
            "Susamaya Wardana College": null,
            "Thurstan College, Colombo": null,
            "Taxila Central College	Horana": null,
            "Veluwana College, Dematagoda": null,
            "Visakha Vidyalaya, Colombo": null,
            "Vivekananda College Colombo": null,
            "Viharamahadevi Balika Vidyalaya,Kiribathgoda, Kelaniya": null,
            "Zahira College, Colombo": null,
            "Al Hilal Central College , Negombo": null,
            "Al-Mubarak central College, Malwana": null,
            "Bandaranayaika Maha Vidyalaya, Hunupitiya, Wattala": null,
            "Bandaranayake College": null,
            "Bandaranayake Central College, Veyangoda": null,
            "Christ King College, Tudella": null,
            "Dalupatha Maha Vidyalaya, Negombo": null,
            "Davisamara Maha Vidyalaya, Seeduwa (Davisamara College)": null,
            "De Mazenod College, Kandana": null,
            "D. S. Senanayake College Mirigama": null,
            "Ellakkala Maha Vidyalaya, Ellakkala": null,
            "Galahitiyawa Central College, Ganemulla": null,
            "Newstead Girls College, Negombo": null,
            "Rathnavali Balika Vidyalaya, Gampaha": null,
            "St. Marys College, Negombo": null,
            "Gurukula College, Kelaniya": null,
            "Good shepherd girls school, Wattala": null,
            "Harischandra National College Negombo": null,
            "Holy Cross College, Gampaha": null,
            "Kelaniya President College": null,
            "Mahagama Sekara Maha Vidyalaya, Radawana": null,
            "Nalanda (Boys') Central College, Minuwangoda": null,
            "Nalanda (Girls') Central College, Minuwangoda": null,
            "Wisdom College , Negombo": null,
            "Wijayarathnam Hindu National College, Negombo": null,
            "Rathnavali Balika Vidyalaya, Gampaha": null,
            "Regent International College, Gampaha": null,
            "Sailan International School, Seeduwa": null,
            "Sapu / Vishaka Balika Vidyalaya": null,
            "Sri Bodhi College, Gampaha": null,
            "Sri Chandrajothi Navodya Vidyalaya": null,
            "Sri Dharmaloka College Kelaniya": null,
            "Sri Pangnananda Vidyalaya, Seeduwa": null,
            "Sri Sanghabodhi Madya Maha Vidyalaya Nittambuwa": null,
            "Sri Siddhartha Kumara Maha Vidyalaya, Gampaha": null,
            "St. Ann's Balika Maha Vidyalaya, Wattala": null,
            "St. Ann's Daluvakotuva Maha Vidyalaya, Negombo": null,
            "St. Anthony's College, Wattala": null,
            "Thakshila College, Gampaha": null,
            "Vidyadeepa Maha Vidyalaya, Weboda": null,
            "Vidyaloka Maha Vidyalaya - Veyangoda": null,
            "Viharamahadevi Balika Vidyalaya, Kiribathgoda": null,
            "Wijayarathnam Hindu Central College": null,
            "Yasodara Devi Balika Maha Vidyalaya, Gampaha": null,
            "Al-Humaisara National School, Beruwala": null,
            "Ananda Sastralaya National School, Matugama": null,
            "C. W. W. Kannangara Madya Maha Vidyalaya, Mathugama": null,
            "Gurulugomi Vidyalya, Kaluthara": null,
            "Horana Royal College": null,
            "Kalutara Balika National School": null,
            "Kalutara Vidyalaya National School": null,
            "Miriswatta National School, Dodangoda": null,
            "Sri Palee College, Horana": null,
            "Sri Sumangala College, Panadura": null,
            "Sri Sumangala Girls College": null,
            "St. John's College Panadura": null,
            "St. Mary's College, Maggona": null,
            "Taxila Central College, Horana": null,
            "Tissa Maha Vidyalaya": null,
            "Bulathsinhala Central College, Bulathsinhala": null,
            "Panadura Balika Maha Vidyalaya, Panadura": null,
            "Bandaragama national school": null,
            "Gamini Center College , Ingiriya": null,
            "Azhar College Akurana": null,
            "Al - Manar National School, Handessa": null,
            "Al Manar Central College, Galhinna": null,
            "Alawathugoda National College, Alawathugoda": null,
            "Ankumbura Parakrama Central College": null,
            "Anuruddha Kumara National School, Nawalapitiya": null,
            "Badi-Ud-Din Balika Vidyalaya, Kandy": null,
            "Dharmaraja College, Kandy": null,
            "D. S. Senanayaka College, Kandy": null,
            "Gamini Dissanayake Model School, Hasalaka": null,
            "Girls' High School, Kandy": null,
            "Hatharaliyadda Central College": null,
            "Kadugannawa Central College": null,
            "Kingston English School, Kandy": null,
            "Kingswood College, Kandy": null,
            "Madina National School, Kandy": null,
            "Mahamaya Girls' College, Kandy": null,
            "Medawala Maha Vidyalaya": null,
            "Menikdiwela Central College": null,
            "Naranwita Maha Vidyalaya": null,
            "Nugawela Central College": null,
            "Poojapitiya M.M.V.": null,
            "Pushpadana Girls' College, Kandy": null,
            "Pussellawa Hindu National School": null,
            "Senadhikara National School, Udahenthenna": null,
            "Sri Rahula College Kandy": null,
            "St. Paul's College Kandy Wariyapola Sri Sumangala College": null,
            "Thalathu Oya Central College": null,
            "S. W. R. D. Bandaranayake National School, Kundasale": null,
            "Ranabima royal college,peradeniya": null,
            "Swarnajothi National School, Kiribathkumbura": null,
            "Teldeniya National School": null,
            "Vidyartha College, Kandy": null,
            "Wickramabahu Central College, Gampola": null,
            "Wimaladharma National School, Atabage": null,
            "Zahira College Matale": null,
            "D.B. Wijethunga National College,Daskara,Muruthagahamula": null,
            "Sussex College Kandy": null,
        },
    });
    $('input#autocomplete-stream').autocomplete({
        data: {
            "Physical Science": null,
            "Bio Science": null,
            "Information & Communication Technology": null,
            "Art": null,
            "Commerce": null,
            "Bio Technology": null,
            "Engineering Technology": null
        },
    });
});